apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-demo
  template:
    metadata:
      labels:
        app: mongo-demo
    spec:
      containers:
        - name: mongo-demo
          image: alidaoud/mongo-demo:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: mongodb://mongo-demo-mongodb:27017/gte3
            - name: SPRING_DATASOURCE_USERNAME
              value: alidaoud
            - name: SPRING_DATASOURCE_PASSWORD
              value: alidaoud
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-demo-service
spec:
  selector:
    app: mongo-demo
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort