apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-demo-db
  name: mongo-demo-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-demo-db
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-demo-db
  labels:
    app: mongo-demo-db
spec:
  selector:
    matchLabels:
      app: mongo-demo-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-demo-db
      name: mongo-demo-db-service


    spec:
      containers:
        - image: mongo:latest
          name: mongo-demo-db

          ports:
            - containerPort: 27017
              name: mongo-demo-db